### ISSUE TITLE
Getting "ghcmod#command#type: Cannot guess type" error for very simple script

### ISSUE THREAD

**Issue by chrissound** [eagletmt/ghcmod-vim#101]
I've got the following script:
_main.hs_:

```
addTwoInt :: Int -> Int -> Int
addTwoInt x y = x + y 

main :: IO ()
main = print $ addTwoInt 5 5
```

On each line I run `:GhcModType` and each response was an error of `ghcmod#command#type: Cannot guess type`.

`$ ghc-mod  check main.hs`
`ghc-mod: /usr/lib/ghc-7.10.3/settings: openFile: does not exist (No such file or directory)`

Perhaps something is wrong with my ghc-mod installation?
Any ideas?

**Comment by chrissound** [comment]
Fixed by running:

```
cabal update
cabal install ghc-mod
```

Initially ran it with stack.

**Comment by AntouanK** [comment]
I have the same error for all types. ( linting works for example )

I've installed with `stack` as well.
I tried installing with cabal, but this is what I get:
![screenshot_2018-01-10_11-00-52](https://user-images.githubusercontent.com/4569111/34769407-a166f0be-f5f5-11e7-887f-5c4c1b2e55e6.png)

**Comment by ecly** [comment]
Same as @AntouanK 

Also wondering why this is the case with the stack installed version but not the cabal version @chrissound?
