### ISSUE TITLE
ghcmod: ghc-mod is not executable

### ISSUE THREAD

**Issue by procuteboy** [eagletmt/ghcmod-vim#45]
when i try to open a haskell file, then vim get the message
"ghcmod: ghc-mod is not executable"
But i try to run ghc-mod in bash, ghc-mod works.

```
ghc-mod version 4.1.0 compiled by GHC 7.6.3
Usage:
......
```

And i try to run

```
:echo executable('ghc-mod')

```

vim gives 

```
0
```

as it for the command

```
:echo vimproc#get_command_name('ghc-mod')

vim gives
E117: Undenfined function: vimproc#get_command_name
E15: Invalid expression: vimproc#get_command_name

```

**Comment by isomorphisms** [comment]
I had the same problem but that solution did not work for me.

**Comment by isomorphisms** [comment]
I guess I needed to `cabal install ghc-mod`. But that sends me to dependency hell.

**Comment by DanielG** [comment]
Just install it in a fresh sandbox somewhere and copy the resulting executable(s) out onto your path ;) As long as you don't try to do that with version > 5.2.1.2 that should work fine.
