### ISSUE TITLE
Version check fails for ghc-mod > 5.0.1

### ISSUE THREAD

**Issue by begriffs** [eagletmt/ghcmod-vim#58]
New versions use version numbers with four components like `5.1.0.1` which breaks an array traversal which is trying to compare with another array containing three numbers.

![1 vim 2014-09-16 20-28-02 2014-09-16 20-30-55](https://cloud.githubusercontent.com/assets/911911/4298135/091ef3aa-3e1b-11e4-811c-efbb7b649a96.jpg)

**Comment by eagletmt** [comment]
Fixed in #57 .
