### ISSUE TITLE
ghcmod-vim opens empty buffer when module 5+ deep

### ISSUE THREAD

**Issue by aaronlevin** [eagletmt/ghcmod-vim#75]
If you are editing a file in a module like `module One.Two.Three.Four.Five.E.hs` and `ghcmod-vim` finds an error, if you press enter in the dialog buffer you will be presented with a blank, empty buffer.

I've created a sample haskell project that reproduces this error. You can see the instructions for cloning and reproducing in the repo:

https://github.com/aaronlevin/ghcmod-vim-issue

> 1. `git clone https://github.com/aaronlevin/ghcmod-vim-issue.git && cd ghcmod-vim-issue`
> 2. `vim src/One/Two/Three/Four/Five/E.hs`
> 3. in vim, make a change that will cause a compilation failure.
> 4. go into the dialog buffer and hit enter to go to the line of code that errors. You should be presented with a blank buffer.

**Comment by eagletmt** [comment]
Confirmed. Interesting bug ...

**Comment by eagletmt** [comment]
Fixed. Thanks for the detailed steps to reproduce.

**Comment by aaronlevin** [comment]
@eagletmt No problem! Thanks for fixing!
