### ISSUE TITLE
quick fix malfunctioning only if cabal is inited

### ISSUE THREAD

**Issue by HuStmpHrrr** [eagletmt/ghcmod-vim#76]
__Problem__: if i run `cabal init` in a project, then suprisingly this plugin failed to popup quickfix window even if `ghc-mod` reports error.

__Environment__:
```
The Glorious Glasgow Haskell Compilation System, version 7.10.1

cabal-install version 1.22.6.0
using version 1.22.2.0 of the Cabal library
```
about `ghc-mod`, since `cabal install ghc-mod` can't be use to install this module anymore, i compiled it myself using master branch.

__Test structure__: single file `Test.hs`:
```haskell
module Test where
1
foo = 1
```
and put it in `Test.hs`.

Reproducing steps:

1 . run the following:
```bash
# create the Test.hs file first in pwd
mkdir TestProj
cd TestProj
cabal init # finish it, choose src/ to be src folder
cp ../Test.hs src/
```

2 . get in two instances of vim's:
```bash
vim src/Test.hs # first
vim ../Test.hs    # second
```
3 . run `:GhcModCheck` in both instances.

what i saw here was the second instance had quick fix window while the first one didn't.

__Probe__: I added some echo in `ghcmod#parse_make` function and i found in first instance, the following was passed in as `a:lines` param:
```
['Warning: Could not find a component assignment, falling back to guessed GHC', '         options.', 'src/Test.hs:2
:1:Parse error: naked expression at top level
Perhaps you intended to use TemplateHaskell']
```
as __stdout__ which is wrong.

therefore in `qflist`, i see:
```
[{'bufnr': 0, 'type': 'E', 'text': 'parse error in ghcmod! Could not parse the following ghc-mod output:Warning: Co
uld not find a component assignment, falling back to guessed GHC'}]
```
so here is the __problem__, which is `ghcmod-vim` failed to parse output with cabal inited. a minor side problem should be this error message didn't show up in quickfix window too.

from command line:
```
$ ghc-mod check src/Test.hs 2>/dev/null
src/Test.hs:2:1:Parse error: naked expression at top levelPerhaps you intended to use TemplateHaskell
```

the second instance receives following:
```
['Test.hs:2:1:Parse error: naked expression at top level
Perhaps you intended to use TemplateHaskell']
```
which is correct.

I don't know where could go wrong. it seems stderr was joined. but I can't find any places where stderr was joined. probably it's better for `ghcmod#parse_make` to simply ignore the output that is not recognizable, instead of breaking out of the for loop. or is there any implementation concern that suggest not to do that?

Thanks for your time in advance.

**Comment by nitrix** [comment]
I have the exact same thing here. It's reproducible.

**Comment by eagletmt** [comment]
ghcmod-vim now ignores stderr correctly.
Thanks for the detailed steps to reproduce :heart_eyes:
